version: 9.6.{build}
install:
- sh: >-
    appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe

    rustup-init.exe -y --default-host %TARGET%

    set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

    rustc -V

    cargo -V
build_script:
- sh: cargo build --release
after_test:
- sh: >-
    cargo build --verbose

    cargo test