version: 1.0.{build}
build:
  parallel: true
  verbosity: minimal

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V

test_script:
  - cargo build --verbose
  - cargo run
  - cargo test

build:
  - cargo build --release
