version: 9.6.{build}
install:
- cmd: >-
    appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe

    rustup-init.exe -y

    set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

    rustc -V

    cargo -V
build_script:
- cmd: cargo build --release
- cmd: dir
- cmd: dir target 
after_test:
- cmd: >-
    cargo build --verbose

    cargo test
artifacts:
- path: target\release\ddh
  name: ddh
deploy:
- provider: GitHub
  description: DDH windows build
  auth_token:
    secure: WFr7LYW7Ios3cmmcG1YzM/etQ/xx1yGGlv37J3F9OhVcka5BdZCcTSdSo5MP08/k
  draft: true
  prerelease: false
