[package]
name = "ddh"
version = "0.9.3"
authors = ["Jon Moroney <jmoroney@hawaii.edu>"]

[dependencies]
clap = "2.30.0"
rayon = "1.0"

[profile.release]
lto = true
debug=false
opt-level = 3
codegen-units = 1
