[package]
name = "ddh"
version = "0.9.8"
authors = ["Jon Moroney <jmoroney@hawaii.edu>"]
edition = "2018"

[dependencies]
clap = "2.30.0"
rayon = "1.0"
stacker = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
siphasher = "~0.2.3"

[profile.release]
lto = true
debug=false
